ui-tests/src/main/java/org/openmrs/reference/page/HomePage.java
ui-tests/src/main/java/org/openmrs/reference/page/ManageUsersPage.java
ui-tests/src/test/java/org/openmrs/reference/ManageUsersTest.java

Manage Users Test
Ticket: https://issues.openmrs.org/browse/GCI-4: 
Melange task: https://www.google-melange.com/gci/task/view/google/gci2014/4630092420481024
YouTube Video: http://youtu.be/vJAXKMwN25Y
Five tests: clerk role, doctor role, nurse role, sysadmin role, rename user. (All roles is Organizational, as they combine other basic role)

GCI-4 - Manage Users Test

---

package/pom.xml
pom.xml

re-added chartsearch module to reference application module

[RA-582] Ensure the Chart Search module is ready for release within OpenMRS 2.2

---

ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

https://issues.openmrs.org/browse/RA-795

RA-795 Automating RA-689 Add diagnosis to Visit Note Test

---

ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/EndVisitTest.java

https://issues.openmrs.org/browse/RA-789

RA-789 Automating RA-717 End Visit Test

---

ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/EndVisitTest.java

https://issues.openmrs.org/browse/RA-786

RA-786 Automating RA-686 Find recently Patient Record Test

---

ui-tests/src/main/java/org/openmrs/reference/helper/TestPatient.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/test/java/org/openmrs/reference/EditDemographicTest.java

https://issues.openmrs.org/browse/RA-788

RA-788.1 Automating RA-718 Edit Demographic Test

---

ui-tests/src/main/java/org/openmrs/reference/page/HomePage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/test/java/org/openmrs/reference/ContactInfoTest.java

https://issues.openmrs.org/browse/RA-818

RA-818 Automating: RA-703 Contact Info Test

---

ui-tests/src/main/java/org/openmrs/reference/page/AppointmentBlocksPage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/CreateAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/EditAppointmentBlockTest.java

https://issues.openmrs.org/browse/RA-824

RA-824 Automating: RA-731 Create Appointment Block Test; RA-732 Edit Appointment Block Test; RA-734 Delete Appointment Block Test

---

ui-tests/src/main/java/org/openmrs/reference/page/FindPatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/FindPatientByFamilyNameTest.java

https://issues.openmrs.org/browse/RA-823

RA-823 Automating: RA-678 Find Patient Record by Family Name Test

---

ui-tests/src/test/java/org/openmrs/reference/StartVisitTest.java

https://issues.openmrs.org/browse/RA-822

RA-822 Automating: RA-699 Start Visit Test

---

ui-tests/src/main/java/org/openmrs/reference/helper/TestPatient.java
ui-tests/src/main/java/org/openmrs/reference/page/FindPatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/test/java/org/openmrs/reference/FindPatientByIdAndNameTest.java

https://issues.openmrs.org/browse/RA-829

RA-829 Automating: RA-679 Register and Find Patient Record by ID or Name or Surname

---

ui-tests/src/main/java/org/openmrs/reference/page/LocationPage.java
ui-tests/src/test/java/org/openmrs/reference/AddLocationTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteLocationTest.java

https://issues.openmrs.org/browse/RA-837

RA-837 Automating: RA-755 Add Location in Location Management; RA-756 Delete Location in Location Management

---

ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/main/java/org/openmrs/reference/page/SettingPage.java
ui-tests/src/test/java/org/openmrs/reference/AutocompleteForNameTest.java

https://issues.openmrs.org/browse/RA-852

RA-852 Automating: RA-752 Auto-complete feature for given and family names Test

---

ui-tests/src/test/java/org/openmrs/reference/ManageProviderSchedulesTest.java

https://issues.openmrs.org/browse/RA-856

RA-856 Automating: RA-710 Manage Provider Schedules Test

---

ui-tests/src/main/java/org/openmrs/reference/page/ConceptFormPage.java
ui-tests/src/test/java/org/openmrs/reference/AddConceptDrugTest.java

https://issues.openmrs.org/browse/RA-858

RA-858 Automating RA-772 Add Concept Drug Test

---

ui-tests/src/main/java/org/openmrs/reference/page/ConceptFormPage.java
ui-tests/src/test/java/org/openmrs/reference/EditConceptTest.java

https://issues.openmrs.org/browse/RA-860

RA-860 Automating: RA-773 Edit Concept Test

---

ui-tests/src/test/java/org/openmrs/reference/EditPhoneNumberTest.java
ui-tests/src/test/java/org/openmrs/reference/XSSOnPhoneNumberFieldTest.java

https://issues.openmrs.org/browse/RA-861

RA-861 Automating: RA-675 XSS On Phone number field test

---

ui-tests/src/main/java/org/openmrs/reference/page/FindPatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/ManageAppointmentPage.java
ui-tests/src/test/java/org/openmrs/reference/AddPatientAppointmentTest.java

https://issues.openmrs.org/browse/RA-862

RA-862 Automating: RA-775 Add Patient Appointment Test

---

ui-tests/src/main/java/org/openmrs/reference/page/ManageUserPage.java
ui-tests/src/main/java/org/openmrs/reference/page/SettingPage.java
ui-tests/src/test/java/org/openmrs/reference/PasswordCannotMatchUsernameTest.java

https://issues.openmrs.org/browse/RA-863

RA-863 Automating RA-781 Password Cannot Match Username Test

---

ui-tests/src/test/java/org/openmrs/reference/ComeBackToApplicationAfterLogoutTest.java

https://issues.openmrs.org/browse/RA-872

RA-872 Automating RA-708 Come back to application after logout Test

---

ui-tests/src/test/java/org/openmrs/reference/NamePatientAccentedLetterTest.java

https://issues.openmrs.org/browse/RA-880

RA-880 Automating RA-677 Names with accented letters are accepted Test

---

ui-tests/src/main/java/org/openmrs/reference/page/ManageUserPage.java
ui-tests/src/test/java/org/openmrs/reference/AddUserTest.java

https://issues.openmrs.org/browse/RA-869

RA-869 Automating: RA-736 Add User in Manage Users Test

---

ui-tests/src/main/java/org/openmrs/reference/page/AllergyPage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/AddNewAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/EditAllergyTest.java

https://issues.openmrs.org/browse/RA-816

Ra 816 Automating: RA-695 Add new Allergy Test; Ra-691 Edit Allegry Test; RA-704 Delete Allergy Test

---

ui-tests/src/main/java/org/openmrs/reference/page/ManageFormsPage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/EyeReportTest.java

https://issues.openmrs.org/browse/RA-830

RA-830 Automating: RA-690 Eye Report Test

---

ui-tests/src/main/java/org/openmrs/reference/page/ConceptFormPage.java
ui-tests/src/main/java/org/openmrs/reference/page/ManageAppointmentPage.java
ui-tests/src/main/java/org/openmrs/reference/page/ManageUserPage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/AddConceptDrugTest.java
ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java
ui-tests/src/test/java/org/openmrs/reference/AddPatientAppointmentTest.java
ui-tests/src/test/java/org/openmrs/reference/AddUserTest.java
ui-tests/src/test/java/org/openmrs/reference/AdmitToInpatientTest.java
ui-tests/src/test/java/org/openmrs/reference/BookRequestAppointmentTest.java
ui-tests/src/test/java/org/openmrs/reference/ComeBackToApplicationAfterLogoutTest.java
ui-tests/src/test/java/org/openmrs/reference/ContactInfoTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteLocationTest.java
ui-tests/src/test/java/org/openmrs/reference/EditAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/EditConceptTest.java
ui-tests/src/test/java/org/openmrs/reference/ExitFromInpatientTest.java
ui-tests/src/test/java/org/openmrs/reference/FindPatientByIdAndNameTest.java
ui-tests/src/test/java/org/openmrs/reference/MergePatientByNameTest.java
ui-tests/src/test/java/org/openmrs/reference/NamePatientAccentedLetterTest.java
ui-tests/src/test/java/org/openmrs/reference/PasswordCannotMatchUsernameTest.java
ui-tests/src/test/java/org/openmrs/reference/PasswordMinimumLengthTest.java
ui-tests/src/test/java/org/openmrs/reference/PasswordRequiresDigitTest.java
ui-tests/src/test/java/org/openmrs/reference/PasswordRequiresNonDigitTest.java
ui-tests/src/test/java/org/openmrs/reference/PasswordUpperAndLowerCaseTest.java
ui-tests/src/test/java/org/openmrs/reference/RecentlyPatientTest.java
ui-tests/src/test/java/org/openmrs/reference/RetireLocationTest.java
ui-tests/src/test/java/org/openmrs/reference/TransferToWardServiceTest.java
ui-tests/src/test/java/org/openmrs/reference/UsingBackButtonInMergePatientTest.java

https://issues.openmrs.org/browse/RA-884

RA-884 Correcting Automated Tests

---

ui-tests/src/main/java/org/openmrs/reference/page/ConceptFormPage.java
ui-tests/src/main/java/org/openmrs/reference/page/DataManagementPage.java
ui-tests/src/main/java/org/openmrs/reference/page/FindPatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/main/java/org/openmrs/reference/page/ServicePage.java
ui-tests/src/test/java/org/openmrs/reference/ActiveVisitsSearchPatientTest.java
ui-tests/src/test/java/org/openmrs/reference/AutocompleteForNameTest.java
ui-tests/src/test/java/org/openmrs/reference/CaptureVitalsTest.java
ui-tests/src/test/java/org/openmrs/reference/DuplicatePatientRegisterTest.java
ui-tests/src/test/java/org/openmrs/reference/FindPatientByFamilyNameTest.java
ui-tests/src/test/java/org/openmrs/reference/ManagePersonTest.java
ui-tests/src/test/java/org/openmrs/reference/ProviderTest.java
ui-tests/src/test/java/org/openmrs/reference/RecordMergeIssueTest.java
ui-tests/src/test/java/org/openmrs/reference/ServiceTest.java
ui-tests/src/test/java/org/openmrs/reference/UsingBackButtonInMergePatientTest.java

https://issues.openmrs.org/browse/RA-884

RA-884.1 Correcting automated tests

---

package/src/main/assembly/assembly.xml

See https://botbot.me/freenode/openmrs/2015-10-26/?msg=52787973&page=3 and subsequent lines for IRC comments about this issue.

Removing WAR file from distribution ZIP

---

ui-tests/src/main/java/org/openmrs/reference/page/ActiveVisitsPage.java
ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/HomePage.java
ui-tests/src/main/java/org/openmrs/reference/page/VisitNotePage.java
ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

Ticket: https://issues.openmrs.org/browse/RA-1087
- Created a new page VisitNotePage, extracted from ClinicianFacingPatientDashboardPage
- Added methods to return pages within ActiveVisitsPage, ClinicianFacingPatientDashboardPage and HomePage

RA-1087 Fix AddDiagnosisToVisitNoteTest to conform to RA-980 guidelines

---

ui-tests/src/test/java/org/openmrs/reference/AddRolesToUserTest.java
ui-tests/src/test/java/org/openmrs/reference/VisitTypeAdministrationTest.java
ui-tests/src/test/java/org/openmrs/reference/XSSOnPhoneNumberFieldTest.java

Refractored VisitTypeAdministrationTest, XSSOnPhoneNumberFieldTest, AddRolesToUserTest according to Guidelines in : https://issues.openmrs.org/browse/RA-980
Subtasks: 
https://issues.openmrs.org/browse/RA-1078
https://issues.openmrs.org/browse/RA-1079
https://issues.openmrs.org/browse/RA-1080

RA-980: fixed VisitTypeAdministrationTest, XSSOnPhoneNumberFieldTest, and AddRolesToUserTest 

---

ui-tests/src/test/java/org/openmrs/reference/AddRolesToUserTest.java
ui-tests/src/test/java/org/openmrs/reference/VisitTypeAdministrationTest.java
ui-tests/src/test/java/org/openmrs/reference/XSSOnPhoneNumberFieldTest.java

Reverts openmrs/openmrs-distro-referenceapplication#112

Revert "RA-980: fixed VisitTypeAdministrationTest, XSSOnPhoneNumberFieldTest, and AddRolesToUserTest "

---

ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

Reverts openmrs/openmrs-distro-referenceapplication#110

Revert "RA-1102 Improved reliability of AddDiagnosisToVisitNoteTest"

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/FindPatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/HomePage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientVisitsDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/main/java/org/openmrs/reference/page/VisitNotePage.java
ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

- Test was unstable, so this test creates a new patient to make the
execution environment more stable
- Constructors fixed to no longer take driver as a parameter
- Cleaned up code style in a few places, i.e. one line functions
- Note: This pull request contains many, if not all of the same changes
found in request #116. If #116 is merged, the number of changed found
in this request should decrease significantly. However, I believe there
is enough new code solving a new problem to merit a standalone pull
request. Please correct me if I am wrong.
- Removed duplicate methods from VisitNotePage

RA 1117 Fix AddDiagnosisToVisitTest

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/FindPatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/HomePage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientVisitsDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/main/java/org/openmrs/reference/page/VisitNotePage.java
ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

Reverts openmrs/openmrs-distro-referenceapplication#117

Revert "RA 1117 Fix AddDiagnosisToVisitTest"

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/EditDemographicsPage.java
ui-tests/src/test/java/org/openmrs/reference/EditDemographicTest.java

Ticket: https://issues.openmrs.org/browse/RA-1110

RA-1110: Fix EditDemographicTest

---

package/src/main/resources/openmrs-distro.properties

reflect the changes in commit 91742b49f9e6399cd0300349f20ca848e4df9011

Remove allergyapi module in openmrs-distro.properties

---

README.md

https://issues.openmrs.org/browse/RA-1178

Add SauceLabs badge to README.md

---

ui-tests/src/main/java/org/openmrs/reference/page/AddEditUserPage.java
ui-tests/src/main/java/org/openmrs/reference/page/AdministrationPage.java
ui-tests/src/main/java/org/openmrs/reference/page/CreateNewUserPage.java
ui-tests/src/main/java/org/openmrs/reference/page/HomePage.java
ui-tests/src/main/java/org/openmrs/reference/page/ManageUserPage.java
ui-tests/src/main/java/org/openmrs/reference/page/SystemAdministrationPage.java
ui-tests/src/test/java/org/openmrs/reference/AddRolesToUserTest.java
ui-tests/src/test/java/org/openmrs/reference/AddUserTest.java
ui-tests/src/test/java/org/openmrs/reference/EditLocationTest.java
ui-tests/src/test/java/org/openmrs/reference/RelationTypeTest.java
ui-tests/src/test/java/org/openmrs/reference/VisitTypeAdministrationTest.java

https://issues.openmrs.org/browse/RA-1078

RA-1078 Fix AddRolesToUserTest

---

.travis.yml

Add $SAUCELABS_USERNAME and $SAUCELABS_ACCESSKEY  environment variables to travis

RA-1177 Run UI tests by travis-ci

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationEditSectionPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/test/java/org/openmrs/reference/XSSOnPhoneNumberFieldTest.java

This PR requires merging [this PR](https://github.com/openmrs/openmrs-contrib-uitestframework/pull/7)

RA-1079 Fixed XSSOnPhoneNumberFieldTest

---

ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

Reverts openmrs/openmrs-distro-referenceapplication#129

Revert "RA-1102 - Fixed reliability of AddDiagnosisToVisitNoteTest"

---

ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

This should work when max timeout will be increased in this PR:
https://github.com/openmrs/openmrs-contrib-uitestframework/pull/9

RA-1102 - Fixed reliability of AddDiagnosisToVisitNoteTest

---

ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

There are some problems with deleting patient after tests, see TODO comments in AddDiagnosisToVisitNoteTest.java for details.
Everything works fine now, except patient deletion after testing.

RA-1102 - Stabilized AddDiagnosisToVisitNoteTest

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientCaptureVitalsPage.java
ui-tests/src/test/java/org/openmrs/reference/CaptureVitalsTest.java

Fixed to fit testing guidelines.

RA-1120 - Fixed CaptureVitalsTest

---

ui-tests/src/test/java/org/openmrs/reference/CaptureVitalsTest.java

Suggested by @rkorytkowski:
> Do not store pages in class fields as it promotes misusage of the uitestframework.

RA-1120 - Moved pages from class fields to local variables

---

.travis.yml

https://issues.openmrs.org/browse/RA-1183

RA-1183 add travis_wait to .travis.yml

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationEditSectionPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/test/java/org/openmrs/reference/ContactInfoTest.java

https://github.com/openmrs/openmrs-module-coreapps/pull/24 is dependency for this PR

RA-1208 - Fixed ContactInfoTest

---

ui-tests/src/main/java/org/openmrs/reference/page/AddEditUserPage.java
ui-tests/src/main/java/org/openmrs/reference/page/AdministrationPage.java
ui-tests/src/main/java/org/openmrs/reference/page/HomePage.java
ui-tests/src/main/java/org/openmrs/reference/page/ManageUserPage.java
ui-tests/src/main/java/org/openmrs/reference/page/SystemAdministrationPage.java
ui-tests/src/test/java/org/openmrs/reference/AddUserTest.java
ui-tests/src/test/java/org/openmrs/reference/MergePatientByNameTest.java
ui-tests/src/test/java/org/openmrs/reference/RecordMergeIssueTest.java
ui-tests/src/test/java/org/openmrs/reference/UsingBackButtonInMergePatientTest.java

Takes about 2 minutes because of `addEditUserPage.getValidationErrors()` loading time.
No idea why it takes so long, I've used this method before and It never took so long.

RA-1210 - Fixed AddUserTest

---

ui-tests/src/main/java/org/openmrs/reference/page/ManageLocationsPage.java
ui-tests/src/test/java/org/openmrs/reference/AddDeleteLocationTest.java
ui-tests/src/test/java/org/openmrs/reference/RetireLocationTest.java

this PR depends on https://github.com/openmrs/openmrs-contrib-uitestframework/pull/16

RA-1207 fix RetireLocationTest

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationEditSectionPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/test/java/org/openmrs/reference/ContactInfoTest.java

Reverts openmrs/openmrs-distro-referenceapplication#156

Revert "RA-1208 - Fixed ContactInfoTest"

---

ui-tests/pom.xml
ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/VisitNotePage.java
ui-tests/src/test/java/org/openmrs/reference/AddDeleteLocationTest.java
ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

This PR is response for @rkorytkowski code review from https://github.com/openmrs/openmrs-distro-referenceapplication/pull/134
There are issues with test cleanup (See AddDiagnosisToVisitNoteTest.java's tearDown() comments)
I will create ticket for that when issues.openmrs.org will wake up :)
//edit
Bug ticket: https://issues.openmrs.org/browse/RA-1197

RA-1102 - Fixed AddDiagnosisToVisitNoteTest to conform with guidelines

---

ui-tests/src/main/java/org/openmrs/reference/page/AdmitToInpatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/ExitFromInpatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientVisitsDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/AdmitToInpatientTest.java

https://issues.openmrs.org/browse/RA-1213

RA-1213 fix AdmitToInpatientTest

---

ui-tests/src/main/java/org/openmrs/reference/page/AddOrEditAllergyPage.java
ui-tests/src/main/java/org/openmrs/reference/page/AllergyPage.java
ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/AddNewAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/EditAllergyTest.java

https://github.com/openmrs/openmrs-module-allergyui/pull/23 needs to be merged before this one, because of minor interface changes in allergyui

RA-1198 - Fixed Add/Edit/Delete Allergy tests

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java

This PR is dependent by https://github.com/openmrs/openmrs-module-coreapps/pull/25

RA-1208 - Applied more reliable component selection

---

ui-tests/src/main/java/org/openmrs/reference/page/AdministrationPage.java

https://github.com/openmrs/openmrs-module-legacyui/pull/61 needs to be merged before this one

RA-1210 - Fixed cssSelectors reliability

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/RegistrationPage.java
ui-tests/src/test/java/org/openmrs/reference/DuplicatePatientRegisterTest.java

Fixed DuplicatePatientRegisterTest, added assertion

RA-1219:  Fix DuplicatePatientRegisterTest

---

ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

https://issues.openmrs.org/browse/RA-1102

RA-1102 improve reliability of AddDiagnosisToVisitNoteTest

---

ui-tests/src/main/java/org/openmrs/reference/page/AdmitToInpatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/ExitFromInpatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/TransferPatientPage.java
ui-tests/src/main/java/org/openmrs/reference/page/TransferToWardServicePage.java
ui-tests/src/test/java/org/openmrs/reference/AdmitExitInpatientTest.java
ui-tests/src/test/java/org/openmrs/reference/TransferToWardServiceTest.java
ui-tests/src/test/java/org/openmrs/reference/XSSOnPhoneNumberFieldTest.java

https://issues.openmrs.org/browse/RA-1229
This PR depends on PR: https://github.com/openmrs/openmrs-contrib-uitestframework/pull/23

RA-1229 fix TransferToWardServiceTest

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/NamePatientAccentedLetterTest.java

https://issues.openmrs.org/browse/TRUNK-4912?jql=filter%3D12852%20

RA-1226- Fix NamePatientAccentedLetterTest

---

ui-tests/src/test/java/org/openmrs/reference/NamePatientAccentedLetterTest.java

https://issues.openmrs.org/browse/RA-1226

RA-1226 Fix NamePatientAccentedLetterTest

---

ui-tests/src/main/java/org/openmrs/reference/page/ReferenceApplicationLoginPage.java
ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java
ui-tests/src/test/java/org/openmrs/reference/CaptureVitalsTest.java
ui-tests/src/test/java/org/openmrs/reference/EndVisitTest.java
ui-tests/src/test/java/org/openmrs/reference/MergeVisitsTest.java
ui-tests/src/test/java/org/openmrs/reference/ReferenceApplicationTestBase.java
ui-tests/src/test/java/org/openmrs/reference/StartVisitTest.java
ui-tests/src/test/java/org/openmrs/reference/VisitReferenceApplicationTestBase.java
ui-tests/src/test/java/org/openmrs/reference/XSSOnPhoneNumberFieldTest.java

https://issues.openmrs.org/browse/RA-1217

RA-1217 introduce VisitReferenceApplicationTestBase

---

.travis.yml
travis-ci-setup.sh
ui-tests/src/test/java/org/openmrs/reference/CheckModules.java
ui-tests/src/test/java/org/openmrs/reference/LoginTest.java

https://issues.openmrs.org/browse/RA-1179

RA-1179 run UI Tests on local dockerized instance of OpenMRS on Travis CI

---

ui-tests/src/main/java/org/openmrs/reference/page/AdministrationPage.java
ui-tests/src/main/java/org/openmrs/reference/page/ModulesPage.java
ui-tests/src/test/java/org/openmrs/reference/CheckModulesTest.java

This PR is dependent by: https://github.com/openmrs/openmrs-module-legacyui/pull/62

RA-1236 - Fixed CheckModulesTest fails on fresh distribution

---

ui-tests/src/test/java/org/openmrs/reference/ComeBackToApplicationAfterLogoutTest.java

RA-1237 - Fixed comeBackToApplicationAfterLogoutTest

---

ui-tests/src/main/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/EditVisitNotePage.java
ui-tests/src/main/java/org/openmrs/reference/page/PatientVisitsDashboardPage.java
ui-tests/src/main/java/org/openmrs/reference/page/VisitNotePage.java
ui-tests/src/test/java/org/openmrs/reference/VisitNoteTest.java

This one doesn't work because edit visit diagnoses and delete visit note doesn't work (checked locally and on int02, works fine on demo.openmrs.org)

RA-1223 - Fix VisitNoteTest

---

ui-tests/src/main/java/org/openmrs/reference/page/AppointmentBlocksPage.java
ui-tests/src/main/java/org/openmrs/reference/page/AppointmentSchedulingPage.java
ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/ManageProviderSchedulesTest.java

https://issues.openmrs.org/browse/RA-1240

RA-1240:Fix EditAppointmentBlockTest

---

package/pom.xml
package/src/main/resources/openmrs-distro.properties
pom.xml

Reverts openmrs/openmrs-distro-referenceapplication#204

Revert "OCLM-50 - Add OCL module to Reference Application"

---

ui-tests/src/test/java/org/openmrs/reference/AddNewAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/EditAllergyTest.java

The ignore annotation has been removed since bug fixig RA-1253

Enabling tests on allergy (CreateNewAllergy, EditAllergy, DeleteAllergy)

---

ui-tests/src/test/java/org/openmrs/reference/LoginTest.java

The test case has been fixed, it runs on a local environment

RA1281: removed @Ignore and the test extends ReferenceApplicationTestBase

---

ui-tests/src/main/java/org/openmrs/reference/page/AppointmentBlocksPage.java
ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/ManageProviderSchedulesTest.java

Reverts openmrs/openmrs-distro-referenceapplication#214

Revert "RA-1320: Tests for Manage Provider Schedule refactored and enabled"

---

.travis.yml
README.md
package/pom.xml
package/src/main/resources/readme.txt
pom.xml
puppet/modules/apache2/files/etc/sites-available/ci-stg.openmrs.org
puppet/modules/aptitude/files/etc/apt/sources.list
puppet/modules/mysql/files/etc/mysql/my.cnf
puppet/modules/tomcat7/templates/etc/default/tomcat7.erb
travis_trigger.sh
travis_wait.sh
ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java
ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteFormTest.java
ui-tests/src/test/java/org/openmrs/reference/EditFormTest.java
ui-tests/src/test/java/org/openmrs/reference/EyeReportTest.java
ui-tests/src/test/java/org/openmrs/reference/FindPatientByNameTest.java
ui-tests/src/test/java/org/openmrs/reference/ManageProviderSchedulesTest.java
ui-tests/src/test/java/org/openmrs/reference/RecordMergeIssueTest.java
ui-tests/src/test/java/org/openmrs/reference/UsingBackButtonInMergePatientTest.java
ui-tests/src/test/java/org/openmrs/reference/page/AppointmentBlocksPage.java
ui-tests/src/test/java/org/openmrs/reference/page/FindPatientPage.java
ui-tests/src/test/java/org/openmrs/reference/page/VisitNotePage.java

This removes trailing whitespace from source files. 
I used `find . -type f  ! -path ./.git/* -exec perl -p -i -e "s/[ \t]$//g" {} \;` to remove the trailing whitespace.

remove trailing whitespace

---

pom.xml

@ssmusoke  , @raff Can you please review this and see if i need to add anything ,thanks

Updated Distro pom.xml to latest module versions as of 2.7

---

pom.xml

This is needed for openmrs-owa-orderentry to work

Upgrade webservices version to 2.23.0-SNAPSHOT

---

pom.xml

RA-1571: Add Attachments module to Reference Application Distribution(Follow-up commit)

RA-1571: Add Attachments module to Reference Application Distribution(Follow-up commit)

---

pom.xml

See '[Attachments: Error 415 (Unsupported Media Type)](https://talk.openmrs.org/t/attachments-error-415-unsupported-media-type/22244/8?u=mksd)'.

RA-1571: Upping Attachments to release 2.1.0.

---

.travis.yml
package/src/main/resources/openmrs-distro.properties
pom.xml
travis_script.sh

Ticket :https://issues.openmrs.org/browse/RA-1632
Remove Chat search Module from the Reff App distro

RA-1632 : Remove Chat search Module from the Reff App distro

---

pom.xml

Ticket :https://issues.openmrs.org/browse/RA-1692
Upgrade coreapps and Attachments version

RA-1692: Upgrade coreapps and Attachments version

---

pom.xml

Ticket : https://issues.openmrs.org/browse/RA-1688
we need to still further raduce the  #body-wrapper padding , so we need more fix in the Ui commons ,hence we need to depend on the latest snapshot of Ui commons

upgrade ui commons to the lastest snapshot

---

pom.xml

Ticket : https://issues.openmrs.org/browse/RA-1686

RA-1686 : Update Ref App to run on Platform 2.3.0 Full version

---

pom.xml

Updated the reference application distro module version
https://issues.openmrs.org/browse/RA-1733
cc @mozzy

RA-1733:Upgrade Reference Aplication distro Module Versions

---

pom.xml

https://issues.openmrs.org/browse/RA-1818

RA-1818:Revert openmrsVersion From 2.4.0-SNAPSHOT to 2.3.0 for REF-APP 2.11.0

---

pom.xml

RA-1818:Followup commit 

---

pom.xml

Reverts openmrs/openmrs-distro-referenceapplication#273

Revert "RA-1818:Followup commit "

---

pom.xml

Reverts openmrs/openmrs-distro-referenceapplication#272

Revert "RA-1818:Revert openmrsVersion From 2.4.0-SNAPSHOT to 2.3.0 for REF-APP 2.11.0"

---

package/src/main/resources/openmrs-distro.properties
pom.xml

https://issues.openmrs.org/browse/RA-1836

RA-1836:Bundle SPA module into REF-APP 2.11.0

---

pom.xml

https://issues.openmrs.org/browse/RA-1818
Follow up commit for reverting platform version 2.4.0-snapshot 

Followup commit

---

pom.xml

https://issues.openmrs.org/browse/RA-1837

RA-1837:Update Reference Application-distro versions

---

pom.xml

https://issues.openmrs.org/browse/RA-1839

RA-1839:Update Referenceapplication-distro version

---

pom.xml

https://issues.openmrs.org/browse/RA-1842

RA-1842: Follow Update of module versions in Ref-app-distro

---

pom.xml

cc @dkayiwa ,@mozzy
Another change of  reporting version was because it was released yesterday checkout [here](https://github.com/openmrs/openmrs-module-reporting/blob/master/pom.xml)  to comfirm

Reverting platform version to 2.3.2

---

pom.xml
ui-tests/pom.xml

Updated compilation version and maven version.

upgraded jdk-1.8 compilation version + maven 3.1

---

pom.xml

Update Dataexchange from 1.3.5 to 1.3.6

---

pom.xml

Updating fhir2 version to snapshot

---

pom.xml

Update attachment module From 2.3.0-snapshot to 2.4.0

---

pom.xml

Reverting platformVersion from 2.4.0-alpha.2 To 2.3.2

---

pom.xml

Reverts openmrs/openmrs-distro-referenceapplication#294

Revert "upgrade fhir version to latest snapshot"

---

ui-tests/src/test/java/org/openmrs/reference/page/AdministrationPage.java

Fixing typo error on administrationPage.
The corresponding commit on the legacyui here https://issues.openmrs.org/browse/LUI-176
cc @k-joseph Kindly review thanks

RATEST-107:Fix Typo error in on admin page in RefApp Distro

---

ui-tests/src/test/java/org/openmrs/reference/EndVisitTest.java
ui-tests/src/test/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java

Ticket id: https://issues.openmrs.org/browse/RATEST-96
Fixed failing test of End Visit test in the legacy ui

RATEST-96: Fixing End Visit Test

---

ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java

Reverts openmrs/openmrs-distro-referenceapplication#334

Revert "RATEST-97:Fix AddDiagnosisToVisitNoteTest"

---

ui-tests/src/test/java/org/openmrs/reference/EndVisitTest.java
ui-tests/src/test/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java

Reverts openmrs/openmrs-distro-referenceapplication#345

Revert "RATEST-96: Fixing End Visit Test"

---

ui-tests/src/test/java/org/openmrs/reference/SearchActiveVisitsTest.java

https://issues.openmrs.org/browse/RATEST-115
cc @k-joseph

RATEST-115:Un Ignore SearchActiveVisitTest

---

ui-tests/src/test/java/org/openmrs/reference/SearchActiveVisitsTest.java

Reverts openmrs/openmrs-distro-referenceapplication#357

Revert "RATEST-115:Un Ignore SearchActiveVisitTest"

---

ui-tests/pom.xml

Ticket ID: https://issues.openmrs.org/browse/RATEST-129
Description:
Failure when resolving arttifacts for referenceapplication-ui-tests module

RATEST-129: Resolving arttifacts for referenceapplication-ui-tests module

---

pom.xml

Follow up commit   https://issues.openmrs.org/browse/RATEST-129

Use https links in POM

---

ui-tests/src/test/java/org/openmrs/reference/EditDemographicTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-144
Description
Fix Edit Demographic Test

RATEST-144: Fix Edit Demographic Test

---

ui-tests/src/test/java/org/openmrs/reference/RegisterUnidentifiedPatientTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-142
Description
Fix Register Unidentified Field Patient Test

RATEST-142: Fix Register UnIdentified Field Patient Test

---

ui-tests/src/test/java/org/openmrs/reference/AdmitExitInpatientTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-136
Description:
Fix Admit Exit Inpatient Test

RATEST-136: Fix Admit Exit Inpatient Test

---

ui-tests/src/test/java/org/openmrs/reference/AddUserTest.java
ui-tests/src/test/java/org/openmrs/reference/page/AdministrationPage.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-135
Description:
Fix Add User Test

RATEST-135: Fix Add User Test

---

ui-tests/src/test/java/org/openmrs/reference/AddDeleteServiceTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-134
Description:
Fix Add Delete Service Test

RATEST-134: Fix Add Delete Service Test

---

ui-tests/src/test/java/org/openmrs/reference/AddUserTest.java
ui-tests/src/test/java/org/openmrs/reference/page/AdministrationPage.java

Reverts openmrs/openmrs-distro-referenceapplication#385

Revert "RATEST-135: Fix Add User Test"

---

ui-tests/src/test/java/org/openmrs/reference/EditServiceTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-123
Description:
Resurrecting Edit Service Test

RATEST-123: Fix Edit Service Test

---

ui-tests/src/test/java/org/openmrs/reference/EditProviderTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-122
Description
Fix Edit Provider Test

RATEST-122: Fix Edit Provider Test

---

ui-tests/src/test/java/org/openmrs/reference/DeletePersonTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-121
Description:
Resurrecting Delete Person Test in the legacy ui

RATEST-121: Fix Delete Person Test

---

ui-tests/src/test/java/org/openmrs/reference/AddProviderTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-120
Description
Fix Add Provider Test in legacy ui

RATEST-120: Fix Add Provider Test

---

ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java
ui-tests/src/test/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-97
Description:
Fix Add Diagnosis To Visit Note Test

RATEST-97: Fix Add Diagnosis To Visit Note Test

---

ui-tests/src/test/java/org/openmrs/reference/AddNewAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/EditAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java

Ticket ID https://issues.openmrs.org/browse/RATEST-131
Description:
Fix Delete Allergy Test

RATEST-131: Fix Delete Allergy Test

---

ui-tests/src/test/java/org/openmrs/reference/SearchActiveVisitsTest.java

https://issues.openmrs.org/browse/RATEST-115
Hope it will work perfect now cc @kaweesi

RATEST-155T:Un ignore Search ActiveVisitTest

---

ui-tests/src/test/java/org/openmrs/reference/AddNewAllergyTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-128
Description
Fix Add New Allergy Test

RATEST-128: Fix Add New Allergy Test

---

ui-tests/src/test/java/org/openmrs/reference/CaptureVitalsTest.java
ui-tests/src/test/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-132
Description:
Fix Capture Vitals Test

RATEST-132: Fix Capture Vitals Test

---

ui-tests/src/test/java/org/openmrs/reference/EditAllergyTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-126
Description:
Fix Edit Allergy Test

RATEST-126: Fix Edit Allergy Test

---

ui-tests/src/test/java/org/openmrs/reference/DeleteRequestAppointmentTest.java
ui-tests/src/test/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-94
Description
Fix Delete Request Appointment Test

RATEST-94: Fix Delete Request Appointment Test

---

ui-tests/src/test/java/org/openmrs/reference/EndVisitTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-145
Description:
Fix End Visit Test

RATEST-145: Fix End Visit Test

---

ui-tests/src/test/java/org/openmrs/reference/EndVisitTest.java

Reverts openmrs/openmrs-distro-referenceapplication#399

Revert "RATEST-145: Fix End Visit Test"

---

ui-tests/src/test/java/org/openmrs/reference/DeleteVisitTypeTest.java
ui-tests/src/test/java/org/openmrs/reference/page/VisitTypeListPage.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-138
Description:
Failing Test on firefox: DeleteVisitTypeTest

RATEST-138: Fix Delete Visit Type Test

---

pom.xml

Update Module versions in distro  cc @sherrif10  @mozzy11 @dkayiwa

Update Module versions in distro

---

ui-tests/src/test/java/org/openmrs/reference/DuplicatePatientRegisterTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-153
Description
Fix duplicate patient register test

RATEST-153: Fix duplicate patient register test

---

ui-tests/src/test/java/org/openmrs/reference/FindPatientByNameTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-141
Description
Fix find patient by name test

RATEST-141: Fix find patient by name test

---

ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java

Reverts openmrs/openmrs-distro-referenceapplication#429

Revert "RATEST-112 - AddEditAppointmentBlockTest"

---

ui-tests/src/test/java/org/openmrs/reference/FindPatientRecordTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-140
Description
Fix find patient record test

RATEST-140: Fix find patient record test

---

ui-tests/src/test/java/org/openmrs/reference/UnidentifiedPatientKeyboardTest.java

Ticket ID: https://issues.openmrs.org/browse/RATEST-82
Description
Fix unindentified patient keyboard test

RATEST-82: Fix unindentified patient keyboard test

---

pom.xml

Updating module versions in distro cc @mozzy11   @dkayiwa

updating module versions in distro

---

ui-tests/src/test/java/org/openmrs/reference/RecordMergeIssueTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-143)
Description -> Fix record merge issue test

RATEST-143: Fix record merge issue test

---

ui-tests/src/test/java/org/openmrs/reference/RecordMergeIssueTest.java

Reverts openmrs/openmrs-distro-referenceapplication#448

Revert "RATEST-143: Fix record merge issue test"

---

ui-tests/src/test/java/org/openmrs/reference/DeleteFormTest.java

https://issues.openmrs.org/browse/RATEST-93 cc @kaweesi

RATEST-93:Failing Test: Delete Form Test

---

ui-tests/src/test/java/org/openmrs/reference/DeleteFormTest.java

Reverts openmrs/openmrs-distro-referenceapplication#423

Revert "RATEST-93:Failing Test: Delete Form Test"

---

package/src/main/resources/openmrs-distro.properties
pom.xml

Bundling the spa module cc @dkayiwa

Bundling SPA Module

---

ui-tests/src/test/java/org/openmrs/reference/AdmitExitInpatientTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-162)
Description -> Fix admit exit inpatient test

RATEST-162: Fix admit exit inpatient test

---

ui-tests/src/test/java/org/openmrs/reference/AddDeleteLocationTest.java
ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java
ui-tests/src/test/java/org/openmrs/reference/AddNewAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/AddPastVisitTest.java
ui-tests/src/test/java/org/openmrs/reference/AddVisitTypeTest.java
ui-tests/src/test/java/org/openmrs/reference/AdmitExitInpatientTest.java
ui-tests/src/test/java/org/openmrs/reference/CaptureVitalsTest.java
ui-tests/src/test/java/org/openmrs/reference/CreatePersonTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteProviderTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteRequestAppointmentTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteVisitTypeTest.java
ui-tests/src/test/java/org/openmrs/reference/DuplicatePatientRegisterTest.java
ui-tests/src/test/java/org/openmrs/reference/EditAllergyTest.java
ui-tests/src/test/java/org/openmrs/reference/EditVisitTypeTest.java
ui-tests/src/test/java/org/openmrs/reference/FindPatientByNameTest.java
ui-tests/src/test/java/org/openmrs/reference/ManageProviderSchedulesTest.java
ui-tests/src/test/java/org/openmrs/reference/MergePatientTest.java
ui-tests/src/test/java/org/openmrs/reference/NamePatientAccentedLetterTest.java
ui-tests/src/test/java/org/openmrs/reference/RetireLocationTest.java
ui-tests/src/test/java/org/openmrs/reference/RetirePersonTest.java
ui-tests/src/test/java/org/openmrs/reference/RetireProviderTest.java
ui-tests/src/test/java/org/openmrs/reference/RetireVisitTypeTest.java
ui-tests/src/test/java/org/openmrs/reference/StartVisitTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-160)
Description:
Refactor the legacy ui tests in respect to the following:
- Removing unwanted `throws`
- Removing redundant `spaces` within the codebase for quality assurance
- Removing unused `imports`
- Organizing `imports` to align with the organization software standards
- Aligning test method `naming` convention
See details [here](https://wiki.openmrs.org/display/docs/Java+Conventions)

RATEST-160: Refactoring legacy ui-tests code base for quality assurance

---

ui-tests/src/test/java/org/openmrs/reference/ComeBackToApplicationAfterLogoutTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-158)
Description -> Refactoring comeBackToApplicationAfterLogout test

RATEST-158: Refactoring comeBackToApplicationAfterLogout test

---

ui-tests/src/test/java/org/openmrs/reference/RegisterPatientTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-159)
Description -> Refactoring register patient test

RATEST-159: Refactoring register patient test

---

ui-tests/src/test/java/org/openmrs/reference/DeleteAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/page/AppointmentBlocksPage.java

Ticket[ ID](https://issues.openmrs.org/browse/RATEST-156)
Description -> Fix delete appointment block test

RATEST-156: Fix delete appointment block test

---

ui-tests/src/test/java/org/openmrs/reference/MergeVisitsTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-85)
Description: Fix merge visits test

RATEST-85: Fix merge visits test

---

ui-tests/src/test/java/org/openmrs/reference/UsingBackButtonInMergePatientTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-81)
Description -> Fix Using back button in merge patient test

RATEST-81: Fix Using back button in merge patient test

---

ui-tests/src/test/java/org/openmrs/reference/TransferToWardServiceTest.java
ui-tests/src/test/java/org/openmrs/reference/page/PatientVisitsDashboardPage.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-83)
Description -> Fix transfer to ward service test

RATEST-83: Fix transfer to ward service test

---

ui-tests/src/test/java/org/openmrs/reference/LoginTest.java

https://issues.openmrs.org/browse/RATEST-111  cc @k-joseph  @kdaud

RATEST-111:Failing Test on firefox: LoginTest

---

ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-112)
Description -> Fix add edit appointment block test, failing test on firefox

Ratest 112 : Failing Test on firefox: AddEditAppointmentBlockTest

---

ui-tests/src/test/java/org/openmrs/reference/page/PatientCaptureVitalsPage.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-151)
Description -> Adding page functionality for consumption by vitals and triaging workflow

RATEST-151: Adding page functionality for consumption by vitals and triaging workflow

---

ui-tests/src/test/java/org/openmrs/reference/FormTest.java
ui-tests/src/test/java/org/openmrs/reference/page/HeaderPage.java

Follow up commit that fixes visibility of logout Element 
https://issues.openmrs.org/browse/RATEST-74

Followup commit to handle logout visibility Exceptions on CI

---

ui-tests/src/test/java/org/openmrs/reference/FormTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-170)
Description -> Temporarily ignore FormTest until further investigation

RATEST-170: Temporarily ignore FormTest until further investigation

---

pom.xml
ui-tests/src/test/java/org/openmrs/reference/page/RegistrationPage.java

This pr handles visibility of phone number label occured while fixing this ticket   https://github.com/openmrs/openmrs-contrib-qaframework/pull/54
Here are the logs that [returned the error to  be fixed](https://github.com/openmrs/openmrs-contrib-qaframework/pull/54/checks?check_run_id=3182664038)  cc @ibacher  @dkayiwa

Adding waiter to fix visibility of phoneNumber label 

---

ui-tests/src/test/java/org/openmrs/reference/BookRequestAppointmentTest.java
ui-tests/src/test/java/org/openmrs/reference/DeleteRequestAppointmentTest.java
ui-tests/src/test/java/org/openmrs/reference/page/AddOrEditAllergyPage.java
ui-tests/src/test/java/org/openmrs/reference/page/AttachmentsPage.java
ui-tests/src/test/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/page/ConditionsPage.java
ui-tests/src/test/java/org/openmrs/reference/page/PatientVisitsDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/page/RequestAppointmentPage.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-154)
Description -> Adding page functionality for consumption by clinical visit workflow

RATEST-154: Adding page functionality for clinical visit test workflow

---

ui-tests/src/test/java/org/openmrs/reference/page/ManageUserAccountPage.java
ui-tests/src/test/java/org/openmrs/reference/page/SystemAdministrationPage.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-157)
Description -> Adding page functionality for manage user account test workflow

RATEST-157: Adding page functionality for manage user test workflow

---

ui-tests/src/test/java/org/openmrs/reference/FormTest.java

Reverts openmrs/openmrs-distro-referenceapplication#523

Revert "RATEST-74:Followup commit ignoring the FormTest"

---

ui-tests/src/test/java/org/openmrs/reference/TransferToWardServiceTest.java
ui-tests/src/test/java/org/openmrs/reference/page/PatientVisitsDashboardPage.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-180)
Description -> Adding page functionality for encounter management test workflow

RATEST-180: Refactoring page element within goToTransferToWardServicePage() to load the right page

---

ui-tests/src/test/java/org/openmrs/reference/ContactInfoTest.java
ui-tests/src/test/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java
ui-tests/src/test/java/org/openmrs/reference/page/RegistrationEditSectionPage.java

https://issues.openmrs.org/browse/RATEST-92  cc @dkayiwa @ibacher  @kdaud 
Opened a new clean Pr
Removed a line  which was showing an assert method that made  the server to take long,it was impossible for the function to add more waiting capabilities for the driver to listen to the assert, so i removed it from the functionality, i would have improved the assertions but the assert at the end of the line causes the server not to quite hence throwing exceptions

RATEST-92:Failing Test: Contact Info Test

---

ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java
ui-tests/src/test/java/org/openmrs/reference/BookRequestAppointmentTest.java
ui-tests/src/test/java/org/openmrs/reference/LoginTest.java
ui-tests/src/test/java/org/openmrs/reference/ManageProviderSchedulesTest.java
ui-tests/src/test/java/org/openmrs/reference/ReferenceApplicationTestBase.java
ui-tests/src/test/java/org/openmrs/reference/RegisterUnidentifiedPatientTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-189)
Description -> Refactor distro tests code indention for quality assurance

RATEST-189: Refactor distro tests code indention for quality assurance

---

ui-tests/src/test/java/org/openmrs/reference/XSSOnPhoneNumberFieldTest.java

https://issues.openmrs.org/browse/RATEST-79  cc @kdaud @gracebish

RATEST-79:Failing Test: XSS On Phone number field test

---

ui-tests/src/test/java/org/openmrs/reference/page/RegistrationPage.java

https://issues.openmrs.org/browse/RATEST-161

RATEST-161:RATEST-161:Adding Relatives Functionality

---

README.md

https://issues.openmrs.org/browse/RATEST-209    cc @Rafal Korytkowski  @dkayiwa  @ibacher

RATEST-209:Remove the source lab tag from readme.file

---

ui-tests/src/test/java/org/openmrs/reference/CheckModulesTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-149)
Description -> Resurrect checkModule test

RATEST-149: Resurrect checkModule test

---

ui-tests/src/test/java/org/openmrs/reference/page/ManageProviderSchedulesPage.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-212)
Description -> Add functionality for manage provider schedules page.
The page functionality in this commit is addressing [RATEST-90](https://issues.openmrs.org/browse/RATEST-90) and [RATEST-91](https://issues.openmrs.org/browse/RATEST-91) in order to resurrect the tests in those ticket.

RATEST-212: Add functionality for manage provider schedules page

---

ui-tests/src/test/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java

[ticket id](https://issues.openmrs.org/browse/RATEST-206) : ndention of deletePatient()

RATEST-206: Check the indention of deletePatient() for quality assurance

---

ui-tests/src/test/java/org/openmrs/reference/BookRequestAppointmentTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-91)
Description -> Resurrect bookRequestApppointment test

RATEST-91: Resurrect bookRequestAppointment test

---

ui-tests/src/test/java/org/openmrs/reference/AddPatientAppointmentTest.java

Fixed the failing firefox tests 
kindly review PR for https://issues.openmrs.org/browse/RATEST-90
@kdaud   @sherrif10

Failing Test: Add Patient Appointment Test

---

ui-tests/src/test/java/org/openmrs/reference/AddPatientAppointmentTest.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-219)
Description -> Refactor the logic of addPatientAppointment test

RATEST-219: Removing an unneeded code line from addPatientAppointment() method

---

ui-tests/src/test/java/org/openmrs/reference/CaptureVitalsTest.java
ui-tests/src/test/java/org/openmrs/reference/page/CaptureVitalsPage.java
ui-tests/src/test/java/org/openmrs/reference/page/PatientCaptureVitalsPage.java

https://issues.openmrs.org/browse/RATEST-231

RATEST-231:Failure when validating the vital value of respiratory rate in CaptureVitalsTest

---

ui-tests/src/test/java/org/openmrs/reference/page/ConfigureMetadataPage.java
ui-tests/src/test/java/org/openmrs/reference/page/ManageLocationAttributeTypesPage.java
ui-tests/src/test/java/org/openmrs/reference/page/ManageLocationTagsPage.java
ui-tests/src/test/java/org/openmrs/reference/page/ManageLocationsPage.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-200)
Description -> Adding page functionality for location workflow test

RATEST-200: Adding page functionality for location workflow test

---

ui-tests/src/test/java/org/openmrs/reference/page/ManageLocationsPage.java

Ticket [ID](https://issues.openmrs.org/browse/RATEST-200)
Description -> Set the true element reference for city_field with in manage locations page

RATEST-200: Set the true element reference for city_field with in manage locations page

---

pom.xml

Updating released versions cc @dkayiwa

Updating released versions

---

pom.xml

Reverts openmrs/openmrs-distro-referenceapplication#567

Revert "Updating released versions"

---

ui-tests/src/test/java/org/openmrs/reference/page/ConditionsPage.java

Adding missing methods due to  https://github.com/openmrs/openmrs-contrib-qaframework/pull/137
cc @kdaud  @dkayiwa @sherrif10

RATEST-225: Adding method for deleting a condition on Conditions Page

---

pom.xml

updating released module versions

updating released module versions

---

pom.xml

Reverts openmrs/openmrs-distro-referenceapplication#571

Revert "updating released module versions"

---

pom.xml

updating next release reff app versions

updating next release reff app versions

---

package/pom.xml
pom.xml
ui-tests/pom.xml
ui-tests/src/test/java/org/openmrs/reference/page/PatientCaptureVitalsPage.java

Removed try-catch blocks.........which in catch blocks returned nothing...
After, no Exception was thrown ..in running the **CaptureVitalsTest** where the **patientCaptureVitalsPage** is implemented
But one test `checkModulesTest` was failing in IDE but passing on` Github actions and bamboo ` 
see https://issues.openmrs.org/browse/RATEST-235

RATEST-235: Handled Exceptions in the catch block Method ~ PatientCaptureVitalsPage

---

distro/configuration/concepts/group_session_meta.csv

This adds concepts needed by the group session feature.

(feat) Group Session Meta

---

frontend/spa-build-config.json

This adds @openmrs/esm-fast-data-entry-app and @openmrs/esm-cohort-builder-app to spa-build-config.json so that they will be included in the 3.x ref app
Note that as of writing the cohort-builder-app is not registered on npmjs.com or any other package registry

(chore) Add Fast Data Entry and Cohort Builder to spa-build-config

---

distro/pom.xml

Ticket: https://issues.openmrs.org/browse/RA-1993

RA-1993: Bumping up referencedemodata to 2.0.0-SNAPSHOT

---

distro/pom.xml
pom.xml

Ticket: https://issues.openmrs.org/browse/RA-1994

RA-1994: Upping dependencies to released versions.

---

distro/pom.xml

Ticket: https://issues.openmrs.org/browse/RA-1994

RA-1994: Upping Appointments to 1.6.0.

---

pom.xml

Fixed the Reference Application 2.13.0 module versions.

Fix module versions

---

frontend/spa-build-config.json

Adds the [form builder](https://github.com/openmrs/openmrs-esm-form-builder) microfrontend to the frontend build config.

(chore) Add Form Builder app to frontend build config

---

distro/configuration/ampathforms/adult_NCD_Registration.json
distro/configuration/ampathforms/adult_NCD_Screening.json
distro/configuration/ampathforms/cervical_cancer_screening.json

https://issues.openmrs.org/browse/KH-52
Below Are screen shots of the tests carried out

KH-52: Add hide logic on some of the NCD forms

---

frontend/spa-build-config.json

Removes the immunizations app from the frontend build config.

(chore) Remove Immunizations app from frontend build config

---

distro/pom.xml

Ticket: https://issues.openmrs.org/browse/RA-2002

RA-2002: Upping Reference Demo Data to 2.1.0-SNAPSHOT

---

frontend/my-config.json

https://issues.openmrs.org/browse/KH-54

KH-54: Address level: rename City to Village

---

pom.xml

Fixed the SNAPSHOT version on the webservices module.

fix the webservices module version

---

pom.xml

Fixed the Reference Application version to match the current released version.

Fix the RefApp SNAPSHOT version

---

distro/pom.xml

**Issue worked on:**
https://issues.openmrs.org/browse/COH-52
**Description:**
This PR fixed the issue in [(COH-52)](https://issues.openmrs.org/browse/COH-52) Deploy the v3.4.0 of Cohort Module to dev3.

COH-52 : Update the cohort module version to v3.4.0

---

distro/pom.xml

Ticket: https://issues.openmrs.org/browse/LUI-189

LUI-189: Bumping Idgen to 4.10.0-SNAPSHOT

---

distro/configuration/ampathforms/lab_order_entry_form-core_demo.json

Slack convo: https://openmrs.slack.com/archives/CHP5QAE5R/p1685610215912599

Removed unused field of 'Laboratory Tests' form.

---

distro/distro.properties
distro/pom.xml

feat: add patient flags module to distro

---

distro/distro.properties

Switch the `version` property to something meaningful.

Add version to distro.properties

---

frontend/spa-build-config.json

Adds the [Patient flags](https://github.com/openmrs/openmrs-esm-patient-chart/tree/main/packages/esm-patient-flags-app) app to the frontend build configuration file.
[NPM package](https://www.npmjs.com/package/@openmrs/esm-patient-flags-app)

(chore) Add patient flags app to build config

---

distro/configuration/ampathforms/TestResultsEntryFormv2.json
distro/configuration/ampathforms/lab_order_entry_form-core_demo.json

Updating form names according to their true purpose
**1. Laboratory Tests -> Laboratory Test Orders**
**2. Test Results Entry Form -> Laboratory Test Results**
Link to the thread: https://openmrs.slack.com/archives/CHP5QAE5R/p1692343712006799?thread_ts=1692212676.310419&cid=CHP5QAE5R

(chore) Align lab test Ampath form names.

---

distro/pom.xml

This PR is a followup on this Ticket: https://issues.openmrs.org/browse/LUI-195

Bamp Legacy UI module to 1.16.0-SNAPSHOT.

---

distro/pom.xml

Ticket: 
https://issues.openmrs.org/browse/O3-2565
https://issues.openmrs.org/browse/O3-2566

Upped Legacy UI to 1.16.0 + O3 Forms to 2.2.0.

---

distro/configuration/attributetypes/attribute_types.csv

https://openmrs.atlassian.net/browse/O3-2605

(fix) O3-2605: Update the field type of the Insurance visit attribute

---

frontend/spa-build-config.json

Adds Immunizations app to the import map

Add Immunizations app

---

README.md

Minor edits to improve the grammar while maintaining the meaning.

(chore) Update README.md

---

frontend/spa-assemble-config.json

**What this PR is about?**
This PR adds the  user-onboarding-app to spa-assemble-config.json for user onboarding walkthroughs.
Ticket
[O3-3778](https://openmrs.atlassian.net/browse/O3-3778)
cc : @ibacher @denniskigen @jayasanka-sack 
[O3-3778]: https://openmrs.atlassian.net/browse/O3-3778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(feat) O3-3778 : Add user onboarding app to the spa-assemble-config.json

---

distro/configuration/globalproperties/i18n-core_demo.xml

Added the Vietnamese and removed British English
https://openmrs.atlassian.net/browse/O3-4132

(chore) O3-4132 : Update O3 EMR Languages: Add Vietnamese

---

distro/configuration/encountertypes/encountertypes_core-demo.csv
distro/configuration/metadatatermmappings/metadatatermmappings-core_demo.csv

add bed management ESM
(add new encounter types for Bed Assignment and Cancel ADT)

(feat) O3-3886: Demo Ward App in the Ref App

---

frontend/config-core_demo.json

Reverts openmrs/openmrs-distro-referenceapplication#893

Revert "(chore) O3-4460: Prevent over-dispensing medications"

---

distro/pom.xml

(chore): Bump initializer

---

frontend/spa-assemble-config.json

Restores the:
- Patient list management app for handling list management concerns on the home page
- Patient lists app for managing lists in the patient chart

Restore patient list related frontend modules

---

pom.xml

Switch qa-ref2app to run against platform 2.8.0

Switch qa-ref2app to run against platform 2.8.0

---

distro/pom.xml

Bump content version to 1.4.0-SNAPSHOT

Bump content version to 1.4.0-SNAPSHOT
