openmrs/openmrs-distro-referenceapplication

ui-tests/src/main/java/org/openmrs/reference/page/FindPatientPage.java, ui-tests/src/test/java/org/openmrs/reference/FindPatientRecordTest.java
Hi Tomasz,
I've updated the test, now it use Thread.sleep() with progressive timeout instead of WebDriverWait. But I still think that the previous version should work correct. May be 5 second timeout in line 
WebDriverWait wait = new WebDriverWait(driver, 5) 
was not enough.
=> RA-819: Replace WebDriverWait by Thread.sleep() for waiting result table

ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java
Ticket: https://issues.openmrs.org/browse/RA-1102
- Removed end visit at end of test so that the number of patients in active visits wont decrease
- Detect end visit link (which will always be there if page is returned successfully), rather than success toast
=> RA-1102 Improved reliability of AddDiagnosisToVisitNoteTest

pom.xml
This PR refers to https://github.com/openmrs/openmrs-module-emrapi/pull/98
=> Bump metadatamapping, emrapi, xstream versions due to MAP-19

ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java
Issue was caused by waiting for toast notification element, because there are 15 seconds of maximum timeout by default.
I've just created method in openmrs-contrib-uitestframework that is able to set maximum timeout of waiting for specified element.
See this diagram for details:
(Numbers indicates load time in seconds)
NOTE:
https://github.com/openmrs/openmrs-contrib-uitestframework/pull/8 needs to be merged before this one will work.
=> RA-1102 - Fixed reliability of AddDiagnosisToVisitNoteTest

package/pom.xml, package/src/main/resources/openmrs-distro.properties, pom.xml
This PR adds 1.2-SNAPSHOT version of OpenMRS OCL module to Refapp distro.
@rkorytkowski We should use 1.2 version here instead of SNAPSHOT, but we need to wait for release :)
=> OCLM-50 - Add OCL module to Reference Application

ui-tests/pom.xml
The variable weburl pointed to the old dismissed url int02, it has been updated to point to qa-refapp.
=> RA-1288: Changed weburl from int02 to qa-refapp

ui-tests/src/test/java/org/openmrs/reference/AddProviderTest.java
According to[ comment ](https://issues.openmrs.org/browse/RA-1200)by the @dkayiwa, the test has been enabled again in order to evaluate if it keeps on failing
=> AddProviderTest enabled again

ui-tests/src/main/java/org/openmrs/reference/page/AppointmentBlocksPage.java, ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java, ui-tests/src/test/java/org/openmrs/reference/DeleteAppointmentBlockTest.java, ui-tests/src/test/java/org/openmrs/reference/ManageProviderSchedulesTest.java
According to bug RA-1320 the tests AddEditAppointmentBlockTest.java, DeleteAppointmentBlockTest and ManageProviderSchedulesTest failed. Additionally they share partially the same code. Hence, tests have been refactored. ManageProviderSchedulesTest is the father class  of AddEdit and Delete and set up/tear down the test.
=> RA-1320: Tests for Manage Provider Schedule refactored and enabled

README.md
Ticket: https://issues.openmrs.org/browse/RA-1335
Edit #1
Updated the Readme to reflect that the Vagrant box is no longer maintained, and added OpenMRS SDK as the method to locally build and run the Ref App.
=> RA-1335: Updated readme - Vagrant marked outdated and added SDK

ui-tests/src/main/java/org/openmrs/reference/page/AppointmentBlocksPage.java, ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java, ui-tests/src/test/java/org/openmrs/reference/DeleteAppointmentBlockTest.java, ui-tests/src/test/java/org/openmrs/reference/ManageProviderSchedulesTest.java
AddEditAppointmentBlockTest has been simplified a little since its previous version  (commit dd66608) failed when execute on [SauceLab ](https://travis-ci.org/openmrs/openmrs-distro-referenceapplication/builds/210340302) although it didnt' failed locally.
Please, if the test keeps on failing can we ignore it and see if DeleteAppointmentBlockTest works.
I'm asking for this because  since they share some commonalities, and it might help me to understand why AddEdit fails on Saucelab. (hopefully it works at this time). 
Really hard to debug the test because sauce lab conditions are not reproducible locally.
Aside note: I'd be grateful if you can squash the commits. 
Thank you in advance.
=> RA-1320: Minor refactor of AddEditAppointmentBlockTest

README.md
The reference in the readme.md to the integration server was erroneous because refereed to the old name of the server (int02).
Additionally the flag -Prun test didn't work anymore.
=> RA-1348: updated reference to the integration server

ui-tests/pom.xml
The weburl http:qa-refapp ... caused the rest API to fail locally, updated to https:qa-refapp...
=> RA-1351: Update of weburl to https

pom.xml
The logic module is not deprecated and is no longer part of the ref app distro. Hence all dependencies to it have been removed.
=> Removed logic module as a dependency

package/src/main/resources/openmrs-distro.properties, pom.xml
From Ref App 2.9 onwards, the [attachments module](https://addons.openmrs.org/show/org.openmrs.module.attachments) will officially be a part of the distribution.
Issue: https://issues.openmrs.org/browse/RA-1571
=> RA-1571: Add Attachments module to Reference Application Distribution

pom.xml
After doing a release to maven with Bamboo, FHIR switched to snapshot, so this PR reverts using released stable version.
=> Switching from SNAPSHOT to latest release version of FHIR

pom.xml
Ticket :https://issues.openmrs.org/browse/RA-1686
Reff App 2.10 should run on platform 2.3
=> RA-1686 : Upgrade Reff App 2.10  to run on Platform 2.3

package/src/main/resources/openmrs-distro.sql
https://issues.openmrs.org/browse/TRUNK-4830 introduced Liquibase snapshots on May 13 2020. 
Since then the reference application fails on startup when updating the database.
The reason for this error is that two change sets are missing from the `liquibasechangelog` table.
This commit adds the missing records to the table.
=> TRUNK-4830 add missing references to liquibasechangelog table

ui-tests/src/test/java/org/openmrs/reference/AddDiagnosisToVisitNoteTest.java
Ticket Id:https://issues.openmrs.org/browse/RATEST-97
Description
Fixed AddDiagnosisToVisitNoteTest,things look good locally no breaking tests ,the tests also run as expected on testing in the browser cc @k-joseph
=> RATEST-97:Fix AddDiagnosisToVisitNoteTest

ui-tests/src/test/java/org/openmrs/reference/ReferenceApplicationTestBase.java
Ticket ID: https://issues.openmrs.org/browse/RATEST-124
Description
Failure when retrieving the user Selected-Location element in distro during test builds
=> RATEST-124: Retrieving the user Selected-Location element

ui-tests/src/test/java/org/openmrs/reference/ManageProviderSchedulesTest.java
Ticket ID: https://issues.openmrs.org/browse/RATEST-113
Description:
Tests classes that consumes ManageProviderScheduleTest fails on firefox engine
=> RATEST-113: Failing Test on Firefox

ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java
Removed @ignore tag and the test can pass on both firefox and chrome in both with head and headless states.
[RATEST-112](https://issues.openmrs.org/browse/RATEST-112)
=> RATEST-112 - AddEditAppointmentBlockTest

ui-tests/src/test/java/org/openmrs/reference/FormTest.java
Follow up https://issues.openmrs.org/browse/RATEST-74    
Have ignored this formTest simply to track the logs with in the bamboo that recently broke, Running this test locally passes on both headless to false or true, so am tracking this in bambooo again  , Let us track bamboo failures from this ticket after merge since this runs perfect on chrome and firefox , so its becoming so wierd if it fails on bamboo after its merged 
cc @ibacher  @dkayiwa  @kdaud
=> RATEST-74:Followup commit ignoring the FormTest

ui-tests/src/test/java/org/openmrs/reference/FormTest.java
Follow up https://issues.openmrs.org/browse/RATEST-74
cc @kdaud @dkayiwa @ibacher 
What changed in this pull request
i would not say this would be the fix to the bamboo logs directly due to the failures https://ci.openmrs.org/browse/REFAPP-UI-428 , however this should fix the ci to green without causing any issues
i deleted the functionality in tear down part of extending the automation to headerPage which is resulting into the failures on bamboo by the visibility of an element. One easiest and clean way is to add the delete function in tear down part, this could be the right and easiest way to fix this without harming anything and leaving all the functionalities working as expected
=> Use HomePage.go()  Instead of HeaderPage.clickOnHomeLink()

ui-tests/src/test/java/org/openmrs/reference/AddPatientAppointmentTest.java, ui-tests/src/test/java/org/openmrs/reference/DeleteRequestAppointmentTest.java
This PR addresses --> [ticket](https://issues.openmrs.org/browse/RATEST-213) in trying to replace importation of pages using wild cards with importing of specific pages to be used in **Delete Request Appointment and Add Patient Appointment Tests**  and also remove some unnecessary spaces in the test classes
=> RATEST-213: Explicitly import pages than using wildcard

ui-tests/src/test/java/org/openmrs/reference/page/ConditionsPage.java
**TICKET ID**
https://issues.openmrs.org/browse/RATEST-243
**DESCRIPTION**
To add a visibility element on the `clickInActive` method in `conditions Page` that was causing the build failures [here](https://github.com/openmrs/openmrs-contrib-qaframework/pull/142)
=> RATEST-243 : Adding visibility Element on ClickInActive in conditionsPage

package/distro.properties
This will assist with 2.5 testing, and 2.5 has several features that we want for 3.x features (e.g. form recordable support for Orders, Allergies, and Diagnoses; Referral Orders support).
**Note:** This is mostly a placeholder PR for now; before we merge this, I’ll also update some of the config in the distro.properties file because there’s some metadata I want to add to our dev & demo environments later today.
=> O3-913: Upgrade to Platform 2.5.0-alpha.3

distro/pom.xml
Ticket: https://issues.openmrs.org/browse/RA-1994
=> RA-1994: Downgrading Address Hierarchy to release 2.15.1.

distro/configuration/appointmentservicedefinitions/service_definitions-core_demo.csv
Goal of this PR is to add some more reasonable-sounding options for Appointment Service field options to our Metadata, per https://issues.openmrs.org/browse/O3-1764. 
* I added General Medicine, Outpatient Department, and Rehabilitation as options, and used the code for the "General" service type. 
* I referenced this directory for the Specialty IDs: https://github.com/openmrs/openmrs-distro-referenceapplication/blob/main/distro/configuration/appointmentspecialities/specialities.csv 
* I *retained* the options for "General" and "Malnutrition" just in case these are part of someone's tests or Demo Data (want to keep the scope of this change impact extremely minimal).
=> O3-1764: Added better Appointment Service type demo options

pom.xml
I am switch the https://qa-refapp.openmrs.org/openmrs/login.htm to run against platform 2.6.0-beta.
/cc: @dkayiwa
=> switching qarefapp2 to platform 2.6.0-beta

pom.xml
I am switching the https://qa-refapp.openmrs.org/openmrs/login.htm to run against the newly released **platform 2.6.0**.
=> Switch qa-ref2app to run against platform 2.6.0

pom.xml
**Description of what I changed**
1. I downgraded the platform version from 2.6.0 to 2.5.9 version to support 2.13.0 Reference Application Release.
2. Updated the resent released module versions on the pom.xml distro basing on their release version.
=> fix the RefApp modules versions

distro/configuration/addresshierarchy/addressConfiguration.xml
Currently, the default value for the country field in the address template is `addresshierarchy.cambodia`. This PR fixes the above said default value to the text `Cambodia`.
=> (fix) Updated country default to Cambodia

distro/configuration/ampathforms/TestResultsEntryFormv2
Adds a simple but long Test Results Entry form that can be used to manually report recent lab results for some common test types.
The goal is to unblock groups like Faimer who want to be able to record test results, without hooking up a Lab Reporting System. 
Known deficiencies:
* The date/time stamp from the form SUBMISSION will be applied to the Test concept, even if this is not actually reflective of the Test RESULT TIME. We should come back to this in the near future when we work on improving Past Visits/RDE flows. 
* multiCheckbox was not working in the form builder ([logged here](https://github.com/openmrs/openmrs-esm-form-builder/issues/73)) so for now I was forced to use Radio where Checkbox would be much more appropriate. 
Issue for this PR: …
=> O3-1727: New Test Results Entry form

distro/configuration/ampathforms/lab_order_entry_form-core_demo.json
This PR updates the Laboratory Tests form to include PTT, INR, ECG and CXR per faimer's request. I admit I don't love that something titled "Laboratory Tests" now also has non-Lab-tests in it, but this is all a temporary workaround anyway until we have the Lab Orders & Other Orders working in the Order Basket.  If people are really opposed to this I can always make an additional workaround form like "Other Orders" for things like ECG, CXR, Chest CT, Ultrasounds, etc, but I don't love that this just adds more bandaids.  
I also discovered 3 bugs with the Form Builder save workflow which is why I had to release this as form version 2.2 instead of 2.0 or 2.1.  
Once the form JSON was updated you can see the options showing as expected.
=> O3-2078: Update to Lab Tests example order form

frontend/spa-build-config.json
Adds the [System Admin app](https://github.com/openmrs/openmrs-esm-admin-tools/tree/main/packages/esm-system-admin-app) to the frontend build configuration file.
=> (chore) Add System Admin app to build config

docker-compose-no-volumes.yml
The purpose of this pull request is to create a docker-compose file that can be used to create pre-filled Docker images. The newly added docker-compose file enables the creation of a backend environment without using volumes. With this, we can write a Bamboo job that runs the backend environment, waits for data to be generated, and obtains a Docker image that includes the data.
I have named the file docker-compose-no-volumes.yml. Let me know if there are any suggestions for the file name.
Related talk thread: https://talk.openmrs.org/t/using-pre-filled-docker-images-for-running-e2e-tests/40003
=> Add the docker compose file used for creating pre-filled images

distro/configuration/addresshierarchy/addressConfiguration.xml
Link to the ticket: https://issues.openmrs.org/browse/O3-2281
The default value for the `Country` field is being removed since the Country `Cambodia` doesn't relate to the refapp.
=> (fix) O3-221: Removed the default for the Country field

frontend/spa-build-config.json
Renames the `outpatient` frontend module to `service-queues`, which reflects what the app does better.
Relates to https://github.com/openmrs/openmrs-esm-patient-management/pull/647.
=> (chore) Rename outpatient app to service-queues-app

.github/workflows/e2e-on-release.yml, e2e_test_support_files/README.md, e2e_test_support_files/commit_and_export_images.sh, e2e_test_support_files/docker-compose-build.yml, e2e_test_support_files/docker-compose.yml, e2e_test_support_files/extract_tag_numbers.sh
Ticket: https://issues.openmrs.org/browse/O3-2525
This GitHub Actions workflow, named "Run E2E Tests on Release PRs," serves as Quality Gate `#4` in the [O3 Release QA pipeline](https://docs.google.com/presentation/d/1k3DH74Mz1Afnrgy2MpwR5HQK5vMpVx0pTfN1na62lvI/edit#slide=id.g165af5ac0be_0_24).
The workflow is designed to automate the end-to-end (E2E) testing process for release pull requests (PRs)
that opened in the format described in here: [How to Release the O3 RefApp](https://wiki.openmrs.org/display/projects/How+to+Release+the+O3+RefApp)
The workflow is conditional and **only runs if the pull request title starts with "(release)"**.
Below is an overview of the key components of the workflow:
This job prepares the test environment, extracts version numbers, builds and runs Docker …
=> (test) O3-2525: Add new GH workflow to run E2E on release PRs

.github/workflows/e2e-on-release.yml, e2e_test_support_files/README.md, e2e_test_support_files/extract_tag_numbers.sh
This pull request aims to facilitate the process of checking out to the main branch of the associated mono repository when the corresponding release is a pre-release when running e2e tests. For detailed information, refer to the updated documentation available [here](https://github.com/jayasanka-sack/openmrs-distro-referenceapplication/tree/e2e-refs/e2e_test_support_files#why-check-out-to-the-tags).
=> (chore) Update the E2E job to handle pre release versions

frontend/Dockerfile, frontend/pom.xml, frontend/src/main/assembly/assembly.xml, pom.xml
Apparently I lied and there was more. This adds a POM and some structure to allow us to publish the `spa-assemble-config.json` (with version numbers) and the `spa-build-config.json` files as a Maven artifact.
In CI we will have something like this:
```sh
docker create --name=openmrs-frontend-container openmrs/openmrs-reference-application-3-frontend:nightly
docker cp openmrs-frontend-container:/usr/share/nginx/html/spa-assemble-config.json src/main/resources/spa-assemble-config.json
docker rm openmrs-frontend-container
```
Note that this means that the POM in the `frontend` directory is intended only as a "publication POM" and not a "actual build".
=> O3-2753: Add ability to publish frontend configuration to Maven

README.md, docker-compose.yml, frontend/Dockerfile, frontend/config-core_demo.json
As mentioned in [O3-2948](https://openmrs.atlassian.net/browse/O3-2948), we want to be able to configure for demo data in the frontend. This PR adds the ability to do that.
Tested as follows: 
- hard-code a different brand color in `config-core_demo.json`
- do a `docker-compose build` then `docker-compose up`. 
- verify that a different brand color shows up when going to `http://localhost`
=> (feat) O3-2948 Add frontend config to RefApp

distro/pom.xml
The backend build is failing as there's a mismatch in the FHIR2 module version: https://ci.openmrs.org/browse/O3-BK-22
Caused by: https://github.com/openmrs/openmrs-distro-referenceapplication/commit/71c16efcc22663449ab7b783d689f6f2d1f69a32
Also, I've fixed the cohort module version that has been reverted with https://github.com/openmrs/openmrs-distro-referenceapplication/commit/33934930ed520928b7e1fab283e094dea0884db0
=> (chore) Fix incorrect backend module versions

docker-compose.yml
MariaDB 10.8.2 runs unusably slow on queries with many JOINs. My [previous attempt](https://github.com/openmrs/openmrs-distro-referenceapplication/pull/799) to fix this issue by tuning a DB parameter did not work. There were non-deterministic behaviors that I did not test for, and dev3 is still experiencing the same slowness on this REST endpoint. https://dev3.openmrs.org/openmrs/ws/rest/v1/queue-entry. More details documented in [this ticket](https://openmrs.atlassian.net/browse/O3-3003).
MariaDB's issue tracker has documented the [many JOINs issue](https://jira.mariadb.org/browse/MDEV-28852) as well and has a fix available in later versions. I think upgrading would be the best way to fix this issue (rather than trying to further tune DB parameters). 10.11.7 is currently the newest …
=> O3-3003 (fix) slow queries with many JOINs by upgrading mariadb to version 10.11.7

distro/configuration/ampathforms/TestResultsEntryFormv2-core_demo.json
This PR adds validation to the Laboratory Test Results form that ensures fields of type [number](https://ampath-forms.vercel.app/docs/field-types-reference#number) whose backing concepts don't allow decimal values show an error when decimals are typed in. For example, the backing concept for `Platelets` does not allow decimal values:
This validation logic was recently introduced to the Angular form engine [here](https://github.com/openmrs/openmrs-ngx-formentry/pull/135).
https://github.com/openmrs/openmrs-distro-referenceapplication/assets/8509731/f675af6d-d540-4349-9ac1-e48a4e120a37
This change solves this error shown when submitting the form after filling in values that lie within the related reference ranges for the backing concepts but without taking into account whether the fields …
=> (feat) O3-2972: Validate number fields whose concepts don't allow decimal values

frontend/spa-assemble-config.json
Adds laboratory esm to spa-assemble-config
=> (feat) Add laboratory frontend module to spa-assemble-config

distro/pom.xml
Bumps the appointments module to the latest snapshot to:
- Get in this [fix](https://bahmni.atlassian.net/browse/BAH-3869) which unlocks @ojwanganto's team
- Fixes failing E2E tests in this related [PR](https://github.com/openmrs/openmrs-esm-patient-management/pull/1164) in Patient Management.
=> Bump appointments module to 2.0.0-SNAPSHOT

distro/configuration/globalproperties/globalproperties-core_data.xml
This PR addresses the issue of overlapping visits by setting the visits.allowOverlappingVisits global property to false. By default, this property is set to true in the core, which allows overlapping visits. Changing it to false will prevent overlapping visits, enhancing the accuracy and integrity of visit data.
Ticket: [O3-3499](https://openmrs.atlassian.net/browse/O3-3499)
Discussion: [Slack Discussion](https://openmrs.slack.com/archives/CHP5QAE5R/p1719486297630129)
[O3-3499]: https://openmrs.atlassian.net/browse/O3-3499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Disallow overlapping visits

.github/workflows/e2e-on-release.yml, .github/workflows/e2e-tests-on-commit.yml
https://openmrs.atlassian.net/browse/O3-3560
Most of our repositories currently use actions/upload-artifact@v3 for artifact uploading and actions/download-artifact@v3 for artifact downloading within our CI pipelines. However, an updated version, actions/upload-artifact@v4 and actions/download-artifact@v4, is now available and should be considered for adoption across our projects.
=> (chore) O3-3560: Use latest upload/download-artifact version in GH Actions

frontend/spa-assemble-config.json
The onboarding app was removed in the [3.1.1 release](https://github.com/openmrs/openmrs-distro-referenceapplication/commit/d995e97c4d57f610471c1bea1ff46b10bf3a01fd), and I'm re-adding it with this PR.
=> Add user onboarding app

distro/configuration/ampathforms/Mental Health Assessment Form.json, distro/configuration/encountertypes/encountertypes_core-demo.csv
This PR adds the PHQ-9 Screening Tool form.
https://openmrs.atlassian.net/browse/O3-3717
=> (feat) Add mental health assessment form

distro/configuration/globalproperties/globalproperties-core_demo.xml
Removes the `webp` file extension from the file upload allowlist. `webp` uploads don't work in O3 - see [this thread for context](https://openmrs.slack.com/archives/C02UNMKFH8V/p1730186448154179).
Also, adds `pdf` to the allowlist.
=> Remove webp from extensions allowlist and add pdf

frontend/config-core_demo.json
This will update the Reference Application to use the newly-implemented functionality to restrict visits to those tagged as visit locations (and to default the visit location to the "nearest" visit location associated with the session location), following the O2 Ref App model.
=> (chore) set restrictByVisitLocationTag parameter to true

distro/configuration/ampathforms/ipd_admission_request.json
Link to the ticket: https://openmrs.atlassian.net/browse/O3-4185
https://github.com/user-attachments/assets/185ce0a8-857f-4603-a7ab-ba1098c276f9
=> (feat) O3-4185: Add form for IPD admission

frontend/config-core_demo.json
This PR is created in created to keep the order basket action menu button on top of the `patient-chart-action-items-slot` in response to https://github.com/openmrs/openmrs-esm-patient-chart/pull/2130, where the `order` property of the `order-basket-action-menu` was removed to allow multiple slots for the extension mentioned above.
https://github.com/user-attachments/assets/a0ba4d7c-7331-4b1c-b220-8badd067d48f
Adding the order basket action menu button to the ward patient workspace
https://github.com/user-attachments/assets/41886c14-853b-415e-ac94-d5d7922eed50
=> Update the patient chart config to order order basket action first

distro/configuration/metadatatermmappings/metadatatermmappings-core_demo.csv
This PR is about mapping metadata for visit note encounter type. It’s needed for this PR: https://github.com/openmrs/openmrs-module-emrapi/pull/250. To access the visit note encounter type, use `emrApiProperties.getVisitNoteEncounterType().getUuid()`.
This PR has two commits:
ecfaffcb2415613936f3d9363f5101140cf2220b : Fix the CSV file. There were missing commas in the file.
76d9f5b79d9fa4cb88f850dcb69e87c785add16f: Add metadata mapping for visit note encounter type.
=> Add metadata mapping for visit note encounter type

distro/configuration/cohorttypes/cohorttypes-core_data.csv
This PR removes the `cohorttypes` folder from the backend configuration since it is already included in the reference application content package - https://github.com/openmrs/openmrs-content-referenceapplication/tree/main/configuration/backend_configuration/cohorttypes
=> (refactor) Remove cohort types config

distro/pom.xml
This PR is an attempt to fix the failing e2e tests by reverting the upgrades to the initializer and core version.
=> Revert initializer and core version bump

distro/pom.xml, frontend/spa-assemble-config.json
This diff does two things:
- Adds the new [reporting](https://github.com/openmrs/openmrs-esm-admin-tools/pull/45) ESM to the spa-assemble-config.json file so it gets included in the distro.
- Updates the `reporting` and `reportingrest` backend modules to newer versions to fix an outdated backend module dependencies warning shown when running the reporting app.
=> Add reporting app to distro and update reporting and reportingrest modules

frontend/config-core_demo.json
Sets the `restrictTotalQuantityDispensed` property to `true` for the dispensing app. This ensures that the user cannot dispense more medications than the quantity prescribed. The dispense order will be marked as Complete once the quantity dispensed matches the quantity prescribed.
See [this issue thread](https://openmrs.atlassian.net/browse/O3-4460) for more context.
=> (chore) O3-4460: Prevent over-dispensing medications

distro/pom.xml
This PR bumps the versions of the demo content package and the required metadata content package, fhir2 and core versions
=> (chore): Bump backend dependencies

distro/pom.xml, frontend/spa-assemble-config.json
This PR removes the following frontend modules from the spa-assemble.config:
- Billing
- Stock management
- Ward 
- Bed management
Should we leave in [the reports app ](https://github.com/openmrs/openmrs-esm-admin-tools/pull/45) that was introduced to the admin tools recently?
=> (chore): Remove unreleased modules

distro/pom.xml
Queue 2.4.0 has a Liquibase error, which was fixed in 2.5.0.
Fix Commit: https://github.com/openmrs/openmrs-module-queue/commit/a7f3aa0c419e45a8f8c357f91ff19c98d85ab13b
Ticket: https://openmrs.atlassian.net/browse/O3-4492
=> O3-4492: Update the Queue module to 2.5.0

distro/pom.xml
- It seems that the API response isn't saving or displaying dateAppointmentScheduled.
- We should update the appointment module version to 2.1.0-SNAPSHOT, as suggested in this [PR](https://github.com/openmrs/openmrs-esm-patient-management/pull/1480).
[Related issue]: [O3-4432](https://openmrs.atlassian.net/browse/O3-4432).
- After upgrading to 2.1.0-SNAPSHOT, the following changes were made to fix the issue.
https://github.com/user-attachments/assets/ab06d2ab-7710-4d22-80eb-9ab99cff0d9c
[O3-4432]: https://openmrs.atlassian.net/browse/O3-4432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (chore) O3-4332 : Update appointments version to 2.1.0-SNAPSHOT

distro/pom.xml
queues module version 2.5.0 had a [critical NPE error](https://openmrs.atlassian.net/browse/O3-4473) when attempting to add queue entries. Bumping it to 2.6.0-SNAPSHOT instead.
=> (chore) update the Queue module to 2.6.0-SNAPSHOT

distro/pom.xml
This PR bumps the version of the content packages to their latest snapshot versions so that PRs such as https://github.com/openmrs/openmrs-content-referenceapplication/pull/2 would be included in dev3.
=> (chore): Bump version of content packages

pom.xml
Switch qa-ref2app to run against platform 2.8.0-alpha release.
=> Switch qa-ref2app to run against platform 2.8.0-alpha

distro/pom.xml
Bump FHIR2 to 2.8.0-SNAPSHOT to get the latest changes that is required for the immunization project. 
Specifically this one: https://github.com/openmrs/openmrs-module-fhir2/pull/574
=> Bump FHIR2 to 2.8.0-SNAPSHOT
